[%hardbreaks]
= BookReview :
== Algorithms to Live By, The Computer Science of Human Decisions
== by Brian Christian and Tom Griffiths
== [http://algorithmstoliveby.com/](http://algorithmstoliveby.com/)

I read this book in the form of an audiobook to make my walks/exercise more palatable. It's a compliment to how interesting and flowing this book is that I hardly cared about the routes my walks were taking. Firstly, we must allow a little leeway to this novel idea that problems in computer science often represent such fundamental problem patterns that they can be extrapolated from and applied to the complex decision making process of human beings. But it does make sense that these patterns exist, and I took the goal of this book to perhaps pick up tricks to make my decision making better. What surprised me was that the authors also used computer algorithms to prove that a lot of human behaviors are optimal by natural design. In essence, the book relies on this sort of analogy to prop up a scaffolding for human behavior and leave curious questions about what mutual benefits this approach might bring to computer science and human behavior.

===  :
1. 37% rule - Say we enter a cas