= An ode to the Art of software engineering
:hp-tags: Software Engineering, Insight, Personal

Coming from a background that sees software as a tool for ‘higher’ purposes - for example, signal processing, hardware engineering and machine learning, the past few months working on various software projects have revealed the amount of thought and design that needs to go into the tooling so that the ‘higher’ goals can be seamlessly expressed and swooned on. Having to deal with inefficiencies and issues with projects has often felt like patching a machine gunned pot of water. And no amount of technical hijinks and quantum mechanics has been able to solve the problems - which has led me to believe that perhaps the technical hammer of Thor is not the only superpower I need.

And so I reluctantly picked up ‘Code Complete’ and tried to elevate my skills from ‘Coder’ to ‘Software Engineer’. After a few pages, I had highlighted almost every line. This is because every salient point seemed to alleviate a pain point I had encountered in the last few months. I felt like a physicist who didn’t know Newtonian physics swinging pendulums in random ways.

Over the next few months, I hope to blog more on the lessons I learn as I try to become better at this job as well as about my interests. For now, I wanted to share my incredulity at the aliquot perspective I had about my own work.
____
“There is a pleasure in the pathless woods,

There is a rapture on the lonely shore,

There is society, where none intrudes,

By the deep Sea, and music in its roar:

I love not Man the less, but Nature more,

From these our interviews, in which I steal

From all I may be, or have been before,

To mingle with the Universe, and feel

What I can ne’er express, yet cannot all conceal.”

Lord Byron
____

-- Anshu