= The Bluster : A Short Story
// See https://hubpress.gitbooks.io/hubpress-knowledgebase/content/ for information about the parameters.
:hp-image: https://images.unsplash.com/photo-1505672678657-cc7037095e60?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2500&q=80
:published_at: 2019-11-26
:hp-tags: Short Story, Blog
// :hp-alt-title: My English Title

“Don’t forget the hat with the straps, it is blustery out there!”, she said, sitting theatrically on her hands to keep them warm. 
“Ushanka”, he muttered, his mind caught by the color coded hurdles of meetings and tasks that lay ahead - his thumbs twitching across the recessed ‘Done’ button on his calendar app.
“What?”
“That’s what the hat is called - an ushanka, it’s Russian I think.”, he said as he made ran through the checklist of things in his pockets and checking if he left the bathroom light on.

Satisfied, he stepped into what was seemingly a clear day devoid of snow that had plagued the city for a week and a half. As he stepped out from his doorstep and under the overpass next to his house, he popped in his earphones and pressed play on a news podcast so that he had something to discuss once he reached the office. Being a man of immense preparation, he expected the cold and wind to hit as he left the shelter of the overpass, and so he braced himself. And indeed, the wind had, in an entropic conspiracy of many scales, profiligated its destructive potential in blowing away the ushanka as soon as it touched it. This led to a hapless reaction and immediate realization that any attempt to recover the hat was futile as it sailed across and around the building.

Defeated, he trudged back homeward into the lobby of his building to find a familiar face in intense argument with an elderly woman.

“The package clearly said 702! I am a biologist and these antibodies are now useless! Did the multiple layers of plastic protection and this conspicuous symbol not alarm you?”, she shrieked.

The elderly woman lulled into an explanation that her medications have a similar symbol, and she wondered if they were refills.

As he made eye contact while passing the duo, he maintained a speed that would allow him to escape getting involved. The voices died down as he reached the elevators, which opened to the frightening growls of a dog that can only be described as carnivorous. And as the elevator provided a brief period of respite until it reopened on another floor, this was soon replaced by the cacophony of two dogs disposing all pretense of civility their owners transmitted through their training.

Finally he reached his floor and walked toward his door. He knew she slept in after he left, her work hours being of a more seasonal nature. So he used his spare key, and entered to find the sheets on his bed in turbulence and more limbs than he had hoped to see. Then he looked out through a window; and there, pushed against the glass was the hat. He opened the window and grabbed it. As he put it on, the buzz of the first meeting starting made his mind up. He stepped out once again, into the bluster.

- Anshuman